import os, glob
import numpy as np

def random_crop(imgs, random_range):
    # Note: image_data_format is 'channel_last'
    # assert img.shape[2] == 3
    height, width = imgs[0].shape

    dx = np.random.random_integers(random_range[0], random_range[1])
    dy = np.random.random_integers(random_range[0], random_range[1])
    x = np.random.randint(0, width - dx + 1)
    y = np.random.randint(0, height - dy + 1)
    
    imgs_crop = []
    for img in imgs: 
        img_tmp = img[y:(y+dy), x:(x+dx)]
        imgs_crop.append(img_tmp)
    return imgs_crop

def crop_generator(batches, crop_length):
    """Take as input a Keras ImageGen (Iterator) and generate random
    crops from the image batches generated by the original iterator.
    """
    while True:
        batch_x, batch_y = next(batches)
        batch_crops = np.zeros((batch_x.shape[0], crop_length, crop_length, 3))
        for i in range(batch_x.shape[0]):
            batch_crops[i] = random_crop(batch_x[i], (crop_length, crop_length))
        yield (batch_crops, batch_y)

